### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by Smokedeuch** [SharkeyMyrl/TFC-TNG-Cellars-Addon#11]
Forge Version:14.23.5.2860
Mod Version:1.24.2

[crash-2022-01-31_17.10.38-client.txt](https://github.com/SharkeyMyrl/TFC-TNG-Cellars-Addon/files/7974826/crash-2022-01-31_17.10.38-client.txt)

**Comment by rShyvers** [comment]
There is a comparability issue with the new forge versions, they changed something. Will continue looking for a fix to get the mod compatible with the newer forge version.

**Comment by rShyvers** [comment]
1.24.3 Released fixing issue.
