### ISSUE TITLE
Crash on entity(player) join world

### ISSUE THREAD

**Issue by Exzept1on** [SharkeyMyrl/TFC-TNG-Cellars-Addon#8]
[crash-2021-12-30_21.59.38-server.txt](https://github.com/SharkeyMyrl/TFC-TNG-Cellars-Addon/files/7793677/crash-2021-12-30_21.59.38-server.txt)

**Comment by ACGaming** [comment]
A Patchouli guide book tries to spawn even when the mod isn't installed, hence causing this crash.
@SharkeyMyrl would have to either add Patchouli as a hard dependency or solve the book granting via code.

**Comment by rShyvers** [comment]
Whoops, my fault had forgotten to implement the try catch to handle patchouli not being present. Fix is present in version 1.24.2
