### ISSUE TITLE
Server crash on start 

### ISSUE THREAD

**Issue by thiago1255** [SharkeyMyrl/TFC-TNG-Cellars-Addon#9]
Forge Version: 1.12.2 - 14.23.5.2860
Mod Version: 1.24.2
Crash Report file: [crash-2022-01-15_19.51.49-server.txt](https://github.com/SharkeyMyrl/TFC-TNG-Cellars-Addon/files/7876037/crash-2022-01-15_19.51.49-server.txt)

**Comment by thiago1255** [comment]
Checking the code and log, i see that error is in:
```
public CellarsTab() {
        super(Reference.MOD_ID);
        setBackgroundImageName("item_search.png");
```
and has i see there are not a file named "item_search.png" on mod

**Comment by rShyvers** [comment]
1.24.3 Released fixing issue.
